INSERT INTO STUDENT VALUES ('1001','Anna','Cl1');
INSERT INTO STUDENT VALUES ('1002','Jhone','Cl1');
INSERT INTO STUDENT VALUES ('1003','ALex','Cl2');
INSERT INTO STUDENT VALUES ('1004','Ivy','Cl2');